import axios from "axios";

const URL = "https://cwbarry.pythonanywhere.com/simple_todo/";

const getTodos = async () => {
  try {
    const res = await axios.get(URL);
    return res.data;
  } catch (error) {
    console.log("Error: " + error);
  }
};

const deleteTodoApi = async (id) => {
  try {
    await axios({
      method: "delete",
      url: `${URL}${id}/`,
    });
  } catch (error) {
    console.log("Error: " + error);
  }
};

// In general, the id is generated by the backend
const addTodoApi = async (todoToStore) => {
  console.log(todoToStore);
  try {
    const res = await axios({
      method: "post",
      url: URL,
      data: todoToStore,
    });
    const storedTodo = res.data;
    return storedTodo;
  } catch (error) {
    console.log("Error: " + error);
  }
};

const editTodoApi = async (todo) => {
  try {
    const res = await axios({
      method: "put",
      url: `${URL}${todo.id}/`,
      data: todo,
    });
  } catch (error) {
    console.log("Error: " + error);
  }
};

const patchTodoDone = async (id, done) => {
  try {
    await axios({
      method: "patch",
      url: `${URL}${id}/`,
      data: { done: done },
    });
  } catch (error) {
    console.log("Error: " + error);
  }
};

export { getTodos, deleteTodoApi, addTodoApi, editTodoApi, patchTodoDone };
